name: Deploy Backend Dev to Homeserver (Self-Hosted)
on:
  push:
    branches: [ dev ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and Restart Container
        run: |
          docker compose -f docker-compose.dev.yml up -d --build
      - name: Cleanup old images
        run: docker image prune -f
